
const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
const REGISTER_USER_SUCCEED = 'REGISTER_USER_SUCCEED'
const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED'

const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
const SIGNIN_SUCCEED = 'SIGNIN_SUCCEED'
const SIGNIN_FAILED = 'SIGNIN_FAILED'

export default{
    REGISTER_USER_REQUEST,
    REGISTER_USER_SUCCEED,
    REGISTER_USER_FAILED,
    
    SIGNIN_REQUEST,
    SIGNIN_SUCCEED,
    SIGNIN_FAILED,
}