
const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
const SIGNIN_FAIL = 'SIGNIN_FAIL'

export default{
    REGISTER_USER_REQUEST,
    REGISTER_USER_SUCCESS,
    REGISTER_USER_FAIL,
    
    SIGNIN_REQUEST,
    SIGNIN_SUCCESS,
    SIGNIN_FAIL,
}