
const GET_LIST_GROUP_REQUEST = 'GET_LIST_GROUP_REQUEST'
const GET_LIST_GROUP_SUCCEED = 'GET_LIST_GROUP_SUCCEED'
const GET_LIST_GROUP_FAILED = 'GET_LIST_GROUP_FAILED'


const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST'
const UPDATE_GROUP_SUCCEED = 'UPDATE_GROUP_SUCCEED'
const UPDATE_GROUP_FAILED = 'UPDATE_GROUP_FAILED'

const DELETE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST'
const DELETE_GROUP_SUCCEED = 'UPDATE_GROUP_SUCCEED'
const DELETE_GROUP_FAILED = 'UPDATE_GROUP_FAILED'

const CREATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST'
const CREATE_GROUP_SUCCEED = 'CREATE_GROUP_SUCCEED'
const CREATE_GROUP_FAILED = 'CREATE_GROUP_FAILED'

const TOGGLE_FROM_GROUP = 'TOGGLE_FROM_GROUP'
export default {

    GET_LIST_GROUP_REQUEST,
    GET_LIST_GROUP_SUCCEED,
    GET_LIST_GROUP_FAILED,

    UPDATE_GROUP_REQUEST,
    UPDATE_GROUP_SUCCEED,
    UPDATE_GROUP_FAILED,

    CREATE_GROUP_REQUEST,
    CREATE_GROUP_SUCCEED,
    CREATE_GROUP_FAILED,

    DELETE_GROUP_REQUEST,
    DELETE_GROUP_SUCCEED,
    DELETE_GROUP_FAILED,

    TOGGLE_FROM_GROUP,
}
