
const GET_LIST_GROUP_REQUEST = 'GET_LIST_GROUP_REQUEST'
const GET_LIST_GROUP_SUCCESS = 'GET_LIST_GROUP_SUCCESS'
const GET_LIST_GROUP_FAIL = 'GET_LIST_GROUP_FAIL'


const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST'
const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS'
const UPDATE_GROUP_FAIL = 'UPDATE_GROUP_FAIL'

const DELETE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST'
const DELETE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS'
const DELETE_GROUP_FAIL = 'UPDATE_GROUP_FAIL'

const CREATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST'
const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS'
const CREATE_GROUP_FAIL = 'CREATE_GROUP_FAIL'

export default {

    GET_LIST_GROUP_REQUEST,
    GET_LIST_GROUP_SUCCESS,
    GET_LIST_GROUP_FAIL,

    UPDATE_GROUP_REQUEST,
    UPDATE_GROUP_SUCCESS,
    UPDATE_GROUP_FAIL,

    CREATE_GROUP_REQUEST,
    CREATE_GROUP_SUCCESS,
    CREATE_GROUP_FAIL,

    DELETE_GROUP_REQUEST,
    DELETE_GROUP_SUCCESS,
    DELETE_GROUP_FAIL,
}
