const GET_MEDIA_PROJECT_REQUEST = 'GET_MEDIA_PROJECT_REQUEST'
const GET_MEDIA_PROJECT_SUCCESS = 'GET_MEDIA_PROJECT_SUCCESS'
const GET_MEDIA_PROJECT_FAIL = 'GET_MEDIA_PROJECT_FAIL'

const GET_LIST_MEDIA_PROJECT_REQUEST = 'GET_LIST_MEDIA_PROJECT_REQUEST'
const GET_LIST_MEDIA_PROJECT_SUCCESS = 'GET_LIST_MEDIA_PROJECT_SUCCESS'
const GET_LIST_MEDIA_PROJECT_FAIL = 'GET_LIST_MEDIA_PROJECT_FAIL'

const UPDATE_MEDIA_PROJECT_REQUEST = 'UPDATE_MEDIA_PROJECT_REQUEST'
const UPDATE_MEDIA_PROJECT_SUCCESS = 'UPDATE_MEDIA_PROJECT_SUCCESS'
const UPDATE_MEDIA_PROJECT_FAIL = 'UPDATE_MEDIA_PROJECT_FAIL'

const DELETE_MEDIA_PROJECT_REQUEST = 'UPDATE_MEDIA_PROJECT_REQUEST'
const DELETE_MEDIA_PROJECT_SUCCESS = 'UPDATE_MEDIA_PROJECT_SUCCESS'
const DELETE_MEDIA_PROJECT_FAIL = 'UPDATE_MEDIA_PROJECT_FAIL'

const CREATE_MEDIA_PROJECT_REQUEST = 'UPDATE_MEDIA_PROJECT_REQUEST'
const CREATE_MEDIA_PROJECT_SUCCESS = 'CREATE_MEDIA_PROJECT_SUCCESS'
const CREATE_MEDIA_PROJECT_FAIL = 'CREATE_MEDIA_PROJECT_FAIL'

const TOGGLE_MEDIA_PROJECT_FORM = 'TOGGLE_MEDIA_PROJECT_FORM'

export default {
    GET_MEDIA_PROJECT_REQUEST,
    GET_MEDIA_PROJECT_SUCCESS,
    GET_MEDIA_PROJECT_FAIL,

    GET_LIST_MEDIA_PROJECT_REQUEST,
    GET_LIST_MEDIA_PROJECT_SUCCESS,
    GET_LIST_MEDIA_PROJECT_FAIL,

    UPDATE_MEDIA_PROJECT_REQUEST,
    UPDATE_MEDIA_PROJECT_SUCCESS,
    UPDATE_MEDIA_PROJECT_FAIL,

    CREATE_MEDIA_PROJECT_REQUEST,
    CREATE_MEDIA_PROJECT_SUCCESS,
    CREATE_MEDIA_PROJECT_FAIL,

    DELETE_MEDIA_PROJECT_REQUEST,
    DELETE_MEDIA_PROJECT_SUCCESS,
    DELETE_MEDIA_PROJECT_FAIL,

    TOGGLE_MEDIA_PROJECT_FORM
}