const GET_REQUEST = 'GET_REQUEST'
const GET_SUCCEED = 'GET_SUCCEED'
const GET_FAILED = 'GET_FAILED'

const GET_LIST_REQUEST = 'GET_LIST_REQUEST'
const GET_LIST_SUCCEED = 'GET_LIST_SUCCEED'
const GET_LIST_FAILED = 'GET_LIST_FAILED'

const UPDATE_REQUEST = 'UPDATE_REQUEST'
const UPDATE_SUCCEED = 'UPDATE_SUCCEED'
const UPDATE_FAILED = 'UPDATE_FAILED'

const DELETE_REQUEST = 'UPDATE_REQUEST'
const DELETE_SUCCEED = 'UPDATE_SUCCEED'
const DELETE_FAILED = 'UPDATE_FAILED'

const CREATE_REQUEST = 'UPDATE_REQUEST'
const CREATE_SUCCEED = 'CREATE_SUCCEED'
const CREATE_FAILED = 'CREATE_FAILED'

const CLEAR_SELECTED = 'CLEAR_SELECTED'

export default {
    GET_REQUEST,
    GET_SUCCEED,
    GET_FAILED,

    GET_LIST_REQUEST,
    GET_LIST_SUCCEED,
    GET_LIST_FAILED,

    UPDATE_REQUEST,
    UPDATE_SUCCEED,
    UPDATE_FAILED,

    CREATE_REQUEST,
    CREATE_SUCCEED,
    CREATE_FAILED,

    DELETE_REQUEST,
    DELETE_SUCCEED,
    DELETE_FAILED,

    CLEAR_SELECTED
}