const GET_REQUEST = 'PLAN_GET_REQUEST'
const GET_SUCCEED = 'PLAN_GET_SUCCEED'
const GET_FAILED = 'PLAN_GET_FAILED'

const GET_LIST_REQUEST = 'PLAN_GET_LIST_REQUEST'
const GET_LIST_SUCCEED = 'PLAN_GET_LIST_SUCCEED'
const GET_LIST_FAILED = 'PLAN_GET_LIST_FAILED'

const UPDATE_REQUEST = 'PLAN_UPDATE_REQUEST'
const UPDATE_SUCCEED = 'PLAN_UPDATE_SUCCEED'
const UPDATE_FAILED = 'PLAN_UPDATE_FAILED'

const DELETE_REQUEST = 'PLAN_UPDATE_REQUEST'
const DELETE_SUCCEED = 'PLAN_UPDATE_SUCCEED'
const DELETE_FAILED = 'PLAN_UPDATE_FAILED'

const CREATE_REQUEST = 'PLAN_UPDATE_REQUEST'
const CREATE_SUCCEED = 'PLAN_CREATE_SUCCEED'
const CREATE_FAILED = 'PLAN_CREATE_FAILED'

const CLEAR_DATA = 'PLAN_CLEAR_DATA'

export default {
    GET_REQUEST,
    GET_SUCCEED,
    GET_FAILED,

    GET_LIST_REQUEST,
    GET_LIST_SUCCEED,
    GET_LIST_FAILED,

    UPDATE_REQUEST,
    UPDATE_SUCCEED,
    UPDATE_FAILED,

    CREATE_REQUEST,
    CREATE_SUCCEED,
    CREATE_FAILED,

    DELETE_REQUEST,
    DELETE_SUCCEED,
    DELETE_FAILED,

    CLEAR_DATA
}