const GET_LIST_REQUEST = 'TODO_GET_LIST_REQUEST'
const GET_LIST_SUCCEED = 'TODO_GET_LIST_SUCCEED'
const GET_LIST_FAILED = 'TODO_GET_LIST_FAILED'


export default {
    GET_LIST_REQUEST,
    GET_LIST_SUCCEED,
    GET_LIST_FAILED,
}