

const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST'
const GET_USER_INFO_SUCCEED = 'GET_USER_INFO_SUCCEED'
const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED'

const UPDATE_USER_INFO_REQUEST = 'UPDATE_USER_INFO_REQUEST'
const UPDATE_USER_INFO_SUCCEED = 'UPDATE_USER_INFO_SUCCEED'
const UPDATE_USER_INFO_FAILED = 'UPDATE_USER_INFO_FAILED'

const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
const CHANGE_PASSWORD_SUCCEED = 'CHANGE_PASSWORD_SUCCEED'
const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED'

export default{

    GET_USER_INFO_REQUEST,
    GET_USER_INFO_SUCCEED,
    GET_USER_INFO_FAILED,

    UPDATE_USER_INFO_REQUEST,
    UPDATE_USER_INFO_SUCCEED,
    UPDATE_USER_INFO_FAILED,

    CHANGE_PASSWORD_REQUEST,
    CHANGE_PASSWORD_SUCCEED,     
    CHANGE_PASSWORD_FAILED
}