const GET_REQUEST = 'GET_USER_REQUEST'
const GET_SUCCEED = 'GET_USER_SUCCEED'
const GET_FAILED = 'GET_USER_FAILED'

const UPDATE_REQUEST = 'UPDATE_USER_REQUEST'
const UPDATE_SUCCEED = 'UPDATE_USER_SUCCEED'
const UPDATE_FAILED = 'UPDATE_USER_FAILED'

const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
const CHANGE_PASSWORD_SUCCEED = 'CHANGE_PASSWORD_SUCCEED'
const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED'

export default{

    GET_REQUEST,
    GET_SUCCEED,
    GET_FAILED,

    UPDATE_REQUEST,
    UPDATE_SUCCEED,
    UPDATE_FAILED,

    CHANGE_PASSWORD_REQUEST,
    CHANGE_PASSWORD_SUCCEED,     
    CHANGE_PASSWORD_FAILED
}