const GET_REQUEST = 'USERS_GET_REQUEST'
const GET_SUCCEED = 'USERS_GET_SUCCEED'
const GET_FAILED =  'USERS_GET_FAILED'

const GET_LIST_REQUEST = 'USERS_GET_LIST_REQUEST'
const GET_LIST_SUCCEED = 'USERS_GET_LIST_SUCCEED'
const GET_LIST_FAILED =  'USERS_GET_LIST_FAILED'

const CREATE_REQUEST = 'USERS_CREATE_REQUEST'
const CREATE_SUCCEED = 'USERS_CREATE_SUCCEED'
const CREATE_FAILED =  'USERS_CREATE_FAILED'

const UPDATE_REQUEST = 'UPDATES_USER_REQUEST'
const UPDATE_SUCCEED = 'UPDATES_USER_SUCCEED'
const UPDATE_FAILED = 'UPDATES_USER_FAILED'

export default{

    GET_REQUEST,
    GET_SUCCEED,
    GET_FAILED,

    GET_LIST_REQUEST,
    GET_LIST_SUCCEED,
    GET_LIST_FAILED,

    CREATE_REQUEST,
    CREATE_SUCCEED,
    CREATE_FAILED,

    UPDATE_REQUEST,
    UPDATE_SUCCEED,
    UPDATE_FAILED
}